[package]
name = "fondu-proxy-rust"
version = "0.1.0"
authors = ["Pablo Mercado"]
edition = "2021"


[dependencies]
serde_json = "1.0.91"
fastly = "^0.9.1"
lol_html = "0.3.2"
url = "2.2.0"
regex = "1.4.2"
serde = "1.0.152"

