# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["Pablo Mercado"]
description = ""
language = "rust"
manifest_version = 2
name = "fondu-proxy-rust"
service_id = ""

[scripts]
  build = "cargo build --bin fondu-proxy-rust --release --target wasm32-wasi --color always"
