# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["Pablo Mercado"]
description = ""
language = "rust"
manifest_version = 2
name = "fondu-proxy-rust"

[scripts]
  build = "cargo build --bin fondu-proxy-rust --release --target wasm32-wasi --color always"

[setup]
	[setup.backends]
		[setup.backends.content]
			description = "backend for the content"
		[setup.backends.fondu]
			description = "backend for the fondu api service"
	[setup.dictionaries]
		[setup.dictionaries.config]
			[setup.dictionaries.config.items]
				[setup.dictionaries.config.items.fondu_path]

[local_server]
	[local_server.backends]
		[local_server.backends.content]
			url = "http://localhost:3000/"
		[local_server.backends.fondu]
			url = "localhost:4000"
		[local_server.dictionaries]
			[local_server.dictionaries.config]
				format = "inline-toml"
				[local_server.dictionaries.config.contents]
						"fondu_path" = "/api"
